const SHEET_ID=PropertiesService.getScriptProperties().getProperty('SHEET_ID');
function doGet(){return HtmlService.createHtmlOutputFromFile('Login').setTitle('2027 수능 고전 어휘 개념어').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}
function db_(){return SpreadsheetApp.openById(SHEET_ID);}
function lock_(fn){const l=LockService.getScriptLock();l.waitLock(20000);try{return fn();}finally{l.releaseLock();}}
function hash_(v){const p=PropertiesService.getScriptProperties();let key=p.getProperty('AUTH_SECRET');if(!key){key=Utilities.getUuid()+Utilities.getUuid();p.setProperty('AUTH_SECRET',key);}return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(String(v),key));}
function literal_(v){return /^[=+@-]/.test(String(v))?"'"+v:String(v);}
function account_(id){const s=db_().getSheetByName('시트1');const rows=s.getDataRange().getDisplayValues(),h=rows.shift(),i=h.indexOf('아이디'),p=h.indexOf('핀번호'),n=h.indexOf('사용자'),a=h.indexOf('활성');if(i<0||p<0)throw Error('아이디·핀번호 열이 없습니다.');const matches=rows.filter(r=>r[i].trim()===id);if(matches.length!==1)return null;const r=matches[0];if(a>=0&&['FALSE','false','아니오','비활성','0'].includes(r[a]))return null;return {id,name:n>=0?r[n]:'',pin:r[p],version:hash_(id+'\n'+r[p])};}
function tab_(a){if(!/^[A-Za-z0-9_.-]{1,70}$/.test(a.id))throw Error('아이디는 영문·숫자·밑줄·점·하이픈 70자 이내로 설정하세요.');const d=db_();let s=d.getSheetByName(a.id);if(!s){s=d.insertSheet(a.id);s.getRange('A1:D2').setValues([['아이디','사용자','최근 접속','현재 완료 수'],[a.id,literal_(a.name),'',0]]);s.getRange('A4:F4').setValues([['기기 이름','최초 등록','최근 접속','상태','기기 식별값','등록 버전']]);s.getRange('D5:D7').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['등록','해제'],true).setAllowInvalid(false).build());s.getRange('A10:F10').setValues([['날짜','최근 접속 시간','테스트한 단어 수','현재 완료 수','정답 수','완료한 테스트 수']]);s.getRange('A1:D1').setBackground('#1c555a').setFontColor('#ffffff').setFontWeight('bold');s.getRange('A4:F4').setBackground('#17838c').setFontColor('#ffffff').setFontWeight('bold');s.getRange('A10:F10').setBackground('#1c555a').setFontColor('#ffffff').setFontWeight('bold');s.setFrozenRows(10);s.setColumnWidths(1,4,170);s.hideColumns(5,2);s.getRange('B5:C7').setNumberFormat('yyyy-mm-dd hh:mm:ss');s.getRange('C2').setNumberFormat('yyyy-mm-dd hh:mm:ss');}if(s.getRange('A2').getDisplayValue()!==a.id)throw Error('동명 탭 충돌: 관리자에게 문의하세요.');s.getRange('B2').setValue(literal_(a.name));return s;}
function today_(){return Utilities.formatDate(new Date(),'Asia/Seoul','yyyy-MM-dd');}
function daily_(s,a){const key='day:'+hash_(a.id)+':'+today_(),p=PropertiesService.getScriptProperties();let v;try{v=JSON.parse(p.getProperty(key)||'null');}catch{}return {key,v:v||{tested:0,correct:0,tests:0}};}
function writeDay_(s,a,metrics,touch){const now=new Date();const state=PropertiesService.getScriptProperties().getProperty('state:'+hash_(a.id))||'[]',count=JSON.parse(state).length;const day=today_();const n=Math.max(0,s.getLastRow()-10);const rows=n?s.getRange(11,1,n,1).getDisplayValues():[];let i=rows.findIndex(r=>r[0]===day);const row=i<0?Math.max(11,s.getLastRow()+1):11+i;if(touch)s.getRange('C2').setValue(now);s.getRange('D2').setValue(count);s.getRange(row,1,1,6).setValues([[day,Utilities.formatDate(now,'Asia/Seoul','HH:mm:ss'),metrics.tested,count,metrics.correct,metrics.tests]]);}
function login(id,pin,remember,device,label){id=String(id||'').trim();pin=String(pin||'');if(!id||id.length>70||pin.length>100||!/^[a-zA-Z0-9-]{20,100}$/.test(device||''))throw Error('로그인 입력을 확인하세요.');return lock_(()=>{const cache=CacheService.getScriptCache(),key='fail:'+hash_(id),fails=Number(cache.get(key)||0);if(fails>=10)throw Error('15분 후 다시 시도하세요.');const a=account_(id);if(!a||hash_(a.pin)!==hash_(pin)){cache.put(key,String(fails+1),900);throw Error('아이디 또는 PIN이 일치하지 않습니다.');}cache.remove(key);const s=tab_(a),rows=s.getRange('A5:F7').getValues(),dh=hash_(device);let slot=rows.findIndex(r=>r[4]===dh&&r[3]==='등록');const now=new Date();if(slot<0){slot=rows.findIndex(r=>r[3]!=='등록');if(slot<0)throw Error('최대 3개 기기가 등록되어 있습니다. 관리자에게 기기 해제를 요청하세요.');rows[slot]=[literal_(String(label||'브라우저').slice(0,80)),now,now,'등록',dh,Utilities.getUuid()];}else rows[slot][2]=now;s.getRange(5+slot,1,1,6).setValues([rows[slot]]);const token=Utilities.getUuid()+Utilities.getUuid(),p=PropertiesService.getScriptProperties();cleanSessions_();p.setProperty('session:'+hash_(token),JSON.stringify({id:a.id,device:dh,generation:rows[slot][5],version:a.version,expiry:Date.now()+(remember?30:1)*86400000}));writeDay_(s,a,daily_(s,a).v,true);return {token,id:a.id};});}
function cleanSessions_(){const p=PropertiesService.getScriptProperties(),all=p.getProperties();for(const k of Object.keys(all)){if(k.startsWith('event:')&&Number(all[k])<Date.now())p.deleteProperty(k);if(k.startsWith('session:')){try{if(JSON.parse(all[k]).expiry<Date.now())p.deleteProperty(k);}catch{p.deleteProperty(k);}}}}
function session_(token,touch){if(typeof token!=='string'||token.length>100)throw Error('다시 로그인하세요.');const p=PropertiesService.getScriptProperties(),raw=p.getProperty('session:'+hash_(token));if(!raw)throw Error('다시 로그인하세요.');const v=JSON.parse(raw),a=account_(v.id);if(v.expiry<Date.now()||!a||a.version!==v.version)throw Error('로그인이 만료되었습니다.');const s=tab_(a),rows=s.getRange('A5:F7').getValues(),i=rows.findIndex(r=>r[3]==='등록'&&r[4]===v.device&&r[5]===v.generation);if(i<0)throw Error('관리자가 이 기기를 해제했습니다.');if(touch)s.getRange(5+i,3).setValue(new Date());return {a,s};}
function loadApp(token){return lock_(()=>{const {a,s}=session_(token,true);writeDay_(s,a,daily_(s,a).v,true);return {id:a.id,html:HtmlService.createHtmlOutputFromFile('App').getContent(),completed:JSON.parse(PropertiesService.getScriptProperties().getProperty('state:'+hash_(a.id))||'[]')};});}
function logout(token){PropertiesService.getScriptProperties().deleteProperty('session:'+hash_(String(token)));return true;}
function heartbeat(token){return lock_(()=>{const {a,s}=session_(token,true);writeDay_(s,a,daily_(s,a).v,true);return true;});}
function recordProgress(token,event){return lock_(()=>{const {a,s}=session_(token,true);if(!event||!['answer','finish','progress'].includes(event.type)||!/^[a-zA-Z0-9-]{8,100}$/.test(event.eventId||''))throw Error('잘못된 기록');const valid=new Set(JSON.parse(HtmlService.createHtmlOutputFromFile('CardIds').getContent()));const ids=[...new Set((event.completed||[]).map(String))];if(ids.length>valid.size||ids.some(id=>!valid.has(id)))throw Error('완료 어휘 오류');const p=PropertiesService.getScriptProperties(),m=daily_(s,a);const ek='event:'+hash_(a.id+':'+event.eventId);if(p.getProperty(ek))return {ok:true};if(event.type==='answer'){if(!valid.has(String(event.cardId))||typeof event.correct!=='boolean')throw Error('문항 오류');m.v.tested++;if(event.correct)m.v.correct++;}if(event.type==='finish')m.v.tests++;p.setProperty('state:'+hash_(a.id),JSON.stringify(ids));p.setProperty(m.key,JSON.stringify(m.v));p.setProperty(ek,String(Date.now()+7*86400000));writeDay_(s,a,m.v,true);return {ok:true};});}
